Update style.css and trail.html
BezzB/Review-one-of-your-past-projects pull request #1
Opened 2023-02-25 13:50 UTC by BezzB

changed updated successfully

2023-02-27 13:46 UTC, BezzB commented on trial.html
> +  <body>
You can use flexbox to be able to place items in good order

2023-02-27 13:46 UTC, BezzB commented on trial.html
> +      <p>The man who saved a billion lives</p>
put this inot a container ```suggestion
    <main id="main">
      <h1 id="title">Dr. Norman Borlaug</h1>
      <p>The man who saved a billion lives</p>
```

2023-02-27 14:44 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @BezzB, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 14:44 UTC, bobb-Rob commented on trial.html
> +  </head>
Based on [your comment](https://github.com/BezzB/Review-one-of-your-past-projects/pull/1/files#r1118755263).

This project is aimed at preparing you to perform very professional code review. You did well using the githb inline comment feature. However, you can improve your comment further, consider the following 👇🏾 
- You should always phrase your comments politely, as suggestions instead of orders. 
- Your comment should always be very clear and easy to understand. Currently, it is not clear which item you are referring to and which position you mean by saying **_good order_**.
- Lastly, your review comment should always include **_Why_**, explaining why the suggested change is necessary.

Using the above three points, see below an example  
> I suggest that you use flexbox in placing the (specific item) in the proper position (specific position- center, left or right) because that is how the item is positioned in the provided template.

2023-02-27 14:44 UTC, bobb-Rob commented on trial.html
> +      <p>The man who saved a billion lives</p>
Based on [your comment](https://github.com/BezzB/Review-one-of-your-past-projects/pull/1/files#r1118755798).

- [ ] Please use the three points I mentioned earlier in my last comment to rephrase your [review comment](https://github.com/BezzB/Review-one-of-your-past-projects/pull/1/files#r1118755798) and remove all typo errors and ambiguity.

2023-02-28 06:39 UTC, wayungi requested changes
Hi @BezzB , 
![image](https://user-images.githubusercontent.com/99656687/220082777-7a0e6a7f-854d-4e32-9c38-3b1eb3b090e4.png)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- [ ] Good use of GitHub features✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 06:39 UTC, wayungi commented on trial.html
> +  <body>
-  [ ] This is a good attempt but we can do better. Your comment `I will suggest you you flexbox as the main container and other items in containers within the flex box for easier management of your site.` is confusing and unclear. It also does not provide an explanation of why the change is necessary. 🤔 . Please write clear comments that explain why the change is needed and keep the tone polite

2023-02-28 06:39 UTC, wayungi commented on trial.html
> +      <p>The man who saved a billion lives</p>
- [ ] the question to answer here is *Why* should the student use `main container`. Please explain why the change is necessary. 👍🏾

2023-02-28 07:43 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @BezzB, 👋 👋 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 08:02 UTC, merged